language: go
go:
  - 1.12

before_install:
  - go get -u -v golang.org/x/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint)
  - go test -v -race ./...